- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

# - include_tasks: Debian.yml
#   when: ansible_os_family == 'Debian'

- include_tasks: Ubuntu20.yml
  when: ansible_distribution == 'Ubuntu'
