---
- name: add key
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://download.docker.com/linux/ubuntu/gpg
    - https://packagecloud.io/AtomEditor/atom/gpgkey

- name: add repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "ppa:ansible/ansible"
    - "ppa:libratbag-piper/piper-libratbag-git"
    - "ppa:linuxuprising/shutter"
    - "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"

- name: update apt cache
  apt:
    update_cache: yes

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - atom
    - python
    - python3
    - htop
    - ansible
    - python3-pip
    - terminator
    - gnome-keyring
    - hunspell-pt-br
    - piper
    - gcc
    - shutter
    - zsh
    - powerline
    - fonts-powerline
    - nextcloud-desktop
    - nautilus-nextcloud
    - caffeine

- name: Download DEB packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - { url: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb', dest: '/opt/' }
    - { url: 'https://download.virtualbox.org/virtualbox/6.1.8/virtualbox-6.1_6.1.8-137981~Ubuntu~eoan_amd64.deb', dest: '/opt/'}
    - { url: 'https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb', dest: '/opt/'}
    - { url: 'https://github.com/ksnip/ksnip/releases/download/v1.8.1/ksnip-1.8.1.deb', dest: '/opt/ksnip.deb' }

- name: Install a .deb package
  apt:
    deb: /opt/{{ item }}
  loop:
    - google-chrome-stable_current_amd64.deb
    - virtualbox-6.1_6.1.8-137981~Ubuntu~eoan_amd64.deb
    - vagrant_2.2.9_x86_64.deb
    - ksnip.deb

- name: install pip modules
  pip:
    name: "{{ item }}"
  loop:
    - docker
    - boto
    - boto3
    - botocore
      #- ovirt-engine-sdk-python
