---
- name: add key
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://download.docker.com/linux/ubuntu/gpg
    - https://packagecloud.io/AtomEditor/atom/gpgkey
    - https://apt.releases.hashicorp.com/gpg

- name: add repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "ppa:ansible/ansible"
    - "ppa:linuxuprising/shutter"
    - "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"
    - "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

- name: update apt cache
  apt:
    update_cache: yes

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - atom
    - python
    - python3
    - htop
    - ansible
    - python3-pip
    - terminator
    - hunspell-pt-br
    - gcc
    - shutter
    - zsh
    - powerline
    - fonts-powerline
    - nextcloud-desktop
    - nautilus-nextcloud
    - caffeine
    - vagrant

- name: Download files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - { url: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb', dest: '/opt/' }
    - { url: 'https://download.virtualbox.org/virtualbox/6.1.22/virtualbox-6.1_6.1.22-144080~Ubuntu~eoan_amd64.deb', dest: '/opt/virtualbox.deb'}
    - { url: 'https://github.com/ksnip/ksnip/releases/download/v1.8.1/ksnip-1.8.1.deb', dest: '/opt/ksnip.deb' }
    - { url: 'https://get.helm.sh/helm-v3.6.0-rc.1-linux-amd64.tar.gz', dest: '/opt/helm.tar.gz' }
    - { url: 'https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl', dest: '/opt/kubectl'}
    - { url: 'https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64', dest: '/opt/minikube'}

- name: Copy kube binaries
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: /usr/local/bin/
    mode: '0755'
  loop:
    - { src: '/opt/kubectl' }
    - { src: '/opt/minikube' }

- name: Extract helm binary
  ansible.builtin.unarchive:
    src: /opt/helm.tar.gz
    dest: /usr/local/bin/

- name: Install a .deb package
  apt:
    deb: /opt/{{ item }}
  loop:
    - google-chrome-stable_current_amd64.deb
    - virtualbox.deb
    - ksnip.deb

- name: install pip modules
  pip:
    name: "{{ item }}"
  loop:
    - docker
    - boto
    - boto3
    - botocore
      #- ovirt-engine-sdk-python

- name: Setting shell to user
  user:
    name: vinicius
    shell: /usr/bin/zsh
