- name: Install Atom packagesdocker
  shell: "apm install {{ item }}"
  loop:
    - atom-beautify
    - atom-marp
    - busy-signal
    - file-icons
    - git-plus
    - gitlab-integration
    - highlight-selected
    - intentions
    - linter
    - linter-ansible-linting
    - linter-ansible-syntax
    - linter-json-lint
    - linter-ui-default
    - linter-terraform-syntax
    - language-docker
    - language-jenkinsfile
    - language-nginx
    - language-terraform
    - remote-editor
